name: Code Verification on Push

on:
  push:
    branches: "**"

jobs:
  check_linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint code
        run: pnpm format:check

  testing:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?pgbouncer=true&connection_limit=1
      DIRECT_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      TESTING_EMAIL: ${{ secrets.TESTING_EMAIL }}
      TESTING_PASSWORD: ${{ secrets.TESTING_PASSWORD }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done

      - name: Run migrations
        run: pnpm db:migrate:dev

      - name: Run tests
        run: pnpm test
